#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 18 19:27:48 2023

@author: james
"""


left, right = 0, len(array) - 1

while left <= right:
    mid = (left + right) / 2
    if array = (left + right) / 2:
        if array[mid] == target:
            return mid
        if array[mid] < target:
            left = mid + 1
        else:
            right = mid - 1