#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 20 14:46:40 2023

@author: james
"""

# 递归 + 记忆化 --》 递推

# 状态的定义： opt[n] , dp[n], fib[n]

# 状态转移方程： opt[n] = best_of(opt[n-1], opt[n-2])

# 最优子结构


# Fib

# def F(n):
F = []
F[0] = 0
F[1] = 1

n =4
for i in range(n):
    F[i] = F[i-1] + F[i-2]
    # return F[n]



# res = F(4)