#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 18 19:42:35 2023

@author: james
"""



# using binary seach for sqrt


def sqrt(n):
    left, right = 0, n
    cigma = 0.001
    while left < right:
        mid = (left+right) / 2
        if -cigma < n - mid ** 2 < cigma:
            return mid
        if n - mid ** 2 > cigma:
            left = mid
        elif n - mid ** 2 < -cigma:
            right = mid



res = sqrt(25)